server:
  port: 8888
spring:
  application:
    name: whiz-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/GuilhermeMelo01/whiz-config-server
#          username: username
#          password: password
          default-label: main
          search-paths:
          - 'greeting-service*'
